language: node_js
node_js:
  - "18"
install:
  - git submodule update --init .
  - npm install
script: npm run build
sudo: false
dist: xenial
addons:
  apt:
    packages:
     - default-jre-headless
     - python-pygments
deploy:
  - provider: script
    script: tools/travis-deploy.sh
    on:
      repo: CindyJS/website
      branch: master
    skip_cleanup: true
