language: node_js
node_js:
  - "18"
before_install:
  - npm i -g npm@8.13.1
install:
  - git submodule update --init .
  - npm install
script: npm run build
sudo: false
dist: xenial 
addons:
  apt:
    packages:
     - default-jre-headless
     - python-pygments
     - gcc-4.9
     - libstdc++6
deploy:
  - provider: script
    script: tools/travis-deploy.sh
    on:
      repo: CindyJS/website
      branch: master
    skip_cleanup: true
