(function(){
'use strict';var aa={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",
arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctan2vec2c:"vec2 arctan2vec2c(vec4 v){\nreturn arctan2c(v.xy,v.zw);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",
blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",
cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn 1./(b.x*b.x+b.y*b.y)*multc(a,vec2(b.x,-b.y));\n}\n",divcv:"vec4 divcv(vec4 a,vec2 b){\nreturn 1./(b.x*b.x+b.y*b.y)*multcv(vec2(b.x,-b.y),a);\n}\n",
expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",
hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",
mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(a.x*b.x-a.y*b.y+0.0000000000000001,a.y*b.x+a.x*b.y);\n}\n",multcv:"vec4 multcv(vec2 a,vec4 b){\nreturn vec4(a.x*b.x-a.y*b.y,a.y*b.x+a.x*b.y,\na.x*b.z-a.y*b.a,a.y*b.z+a.x*b.a);\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",
powi:"float powi(float a,int b){\nreturn pow(a,float(b));\n}\n",random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",
rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",
vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ba=!1,h,m,n,q,r={},u={},ca=!1,da,ea=!1,fa=1,v={},w=[],ga=[];
function ha(){function a(c){h.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ba){h=document.createElement("canvas");h.id="glcanvas";h.style.display="none";h.width=h.height=0;document.body.appendChild(h);m=document.createElement("canvas");m.id="tmpcanvas";m.style.display="none";m.width=m.height=0;document.body.appendChild(m);var b="Unknown";h.addEventListener("webglcontextcreationerror",a,!1);(n=h.getContext("webgl"))||(n=h.getContext("experimental-webgl"));
if(!n)throw new ia("Could not obtain a WebGL context.\nReason: "+b);h.removeEventListener("webglcontextcreationerror",a,!1);ea=n.getExtension("OES_texture_float")&&n.getExtension("OES_texture_float_linear");ea||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(ca=(da=n.getExtension("OES_texture_half_float"))&&n.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),ea=ca=!1,n.getExtension("OES_texture_half_float")&&n.getExtension("OES_texture_half_float_linear")&&n.getExtension("EXT_color_buffer_half_float")?ca=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures."));ba=!0}};function ja(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,d=a.length;c<d;c++)b[c]=ja(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=ja(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function ka(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,d=a.length;c<d;c++)if(!ka(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(d=0;d<c.length;d++){var e=c[d];if(!ka(a[e],b[e]))return!1}return!0}return!1}function la(a){return"number"===typeof a}
function ma(a,b){if(a===b)return!0;if(la(a)||la(b))return a===b;for(var c in a)if(a.hasOwnProperty(c)&&(!b.hasOwnProperty(c)||!ma(a[c],b[c])))return!1;for(var d in b)if(b.hasOwnProperty(d)&&!a.hasOwnProperty(d))return!1;return!0}function na(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function oa(a){if("boolean"===a.ctype)return x;if("number"===a.ctype)return a=a.value,1E-10>Math.abs(a.imag)?(a.real|0)===a.real?y:z:A;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=oa(b[0]),d=1;d<b.length;d++)c=pa(c,oa(b[d]));if(B(c,z)){if(2==b.length)return C;if(3==b.length)return D;if(4==b.length)return F}if(B(c,A)&&2==b.length)return G;if(c===C&&2==b.length)return H;if(c===G&&2==b.length)return qa;if(c===D&&3==b.length)return ra;if(c===F&&4==b.length)return sa}}else if("string"===
a.ctype||"image"===a.ctype)return I;console.error("Cannot guess type of "+JSON.stringify(a));return q}var ta=0;function ua(){ta++;return"_helper"+ta}function va(a,b){if(a>h.width||b>h.height)h.width=Math.ceil(a),h.height=Math.ceil(b)}function wa(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function xa(a){return wa(a,0,a.instance.canvas.clientHeight)}function ya(a){return wa(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}
var Aa=new Float32Array(1),Ba=new Int32Array(Aa.buffer);function Ca(a){Aa[0]=a;a=Ba[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Da(a){if(ea)return new Float32Array(a);if(ca){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=Ca(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Ea(a){return ea?new Float32Array(a):ca?new Uint16Array(a):new Uint8Array(a)}function Fa(){return ea?n.FLOAT:ca?da.HALF_FLOAT_OES:n.UNSIGNED_BYTE}function Ga(a){for(var b=1;b<a;)b<<=1;return b};function Ha(a,b){a.hasOwnProperty("readcanvaswrappers")||(a.readcanvaswrappers=Array(4));var c=2*b.D+b.H;a.readcanvaswrappers.hasOwnProperty(c)||(a.writecanvaswrapper&&a.writecanvaswrapper.generation>a.generation&&a.writecanvaswrapper.J(),a.readcanvaswrappers[c]=new Ia(a,b),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.readcanvaswrappers[c].generation+1)})));a.writecanvaswrapper&&(a.writecanvaswrapper=a.readcanvaswrappers[c]);
return a.readcanvaswrappers[c]}function Ja(a){if(!a.hasOwnProperty("writecanvaswrapper")){var b=-1;if(a.readcanvaswrappers)for(var c=3;0<=c;c--)a.readcanvaswrappers.hasOwnProperty(b)&&(b=c);else a.readcanvaswrappers=Array(4);-1==b&&(c={H:!0,D:!1,repeat:!1},b=2*c.D+c.H,a.readcanvaswrappers[b]=new Ia(a,c));a.writecanvaswrapper=a.readcanvaswrappers[b]}return a.writecanvaswrapper}
function Ia(a,b){this.canvas=a;this.h=b;this.w=a.width;this.s=a.height;Ka(this);this.o=0;this.i=[];this.C=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.cdyUpdate=this.J.bind(this);a=Ea(this.G*this.B*4);for(var c=0;2>c;c++)this.i[c]=n.createTexture(),n.bindTexture(n.TEXTURE_2D,this.i[c]),n.pixelStorei(n.UNPACK_ALIGNMENT,1),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,this.G,this.B,0,n.RGBA,Fa(),a),b.D?n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.H?n.LINEAR_MIPMAP_LINEAR:n.NEAREST_MIPMAP_LINEAR):
n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.H?n.LINEAR:n.NEAREST),n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MAG_FILTER,b.H?n.LINEAR:n.NEAREST),this.C[c]=n.createFramebuffer(),n.bindFramebuffer(n.FRAMEBUFFER,this.C[c]),n.framebufferTexture2D(n.FRAMEBUFFER,n.COLOR_ATTACHMENT0,n.TEXTURE_2D,this.i[c],0);this.v=new La(aa.copytexture_v,aa.copytexture_f);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);a=n.getAttribLocation(this.v.h,"aPos");n.enableVertexAttribArray(a);
c=n.getAttribLocation(this.v.h,"aTexCoord");n.enableVertexAttribArray(c);var d=new Float32Array([0,0,1,0,0,1,1,1]),e=b.byteLength;n.bufferData(n.ARRAY_BUFFER,e+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,0,b);n.bufferSubData(n.ARRAY_BUFFER,e,d);n.vertexAttribPointer(a,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(c,2,n.FLOAT,!1,0,e)}function Ka(a){a.G=Ga(a.w+a.w/2*(a.h.D&&a.h.repeat));a.B=Ga(a.s+a.s/2*(a.h.D&&a.h.repeat))}Ia.prototype.bindTexture=function(){n.bindTexture(n.TEXTURE_2D,this.i[this.o])};
Ia.prototype.bindFramebuffer=function(){n.bindFramebuffer(n.FRAMEBUFFER,this.C[this.o^1]);this.o^=1};Ia.prototype.J=function(){var a;this.canvas.img.hasOwnProperty("getContext")?a=this.canvas.img.getContext("2d"):(this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.w,this.canvas.img.height=this.s,a=this.canvas.img.getContext("2d"));a.clearRect(0,0,this.w,this.s);this.drawTo(a,0,0);this.canvas.img.generation++};
Ia.prototype.drawTo=function(a,b,c){va(this.w,this.s);n.viewport(0,0,this.G,this.B);n.useProgram(this.v.h);n.activeTexture(n.TEXTURE0);n.bindTexture(n.TEXTURE_2D,this.i[this.o]);this.v.i.sampler([0]);n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();a.drawImage(h,0,h.height-this.s,this.w,this.s,b,c,this.w,this.s)};function Ma(a,b){this.l=a;this.o=b;Na(this)}
function Na(a){var b=Oa(new Pa(a.l),a.o);a.i=b.u;a.m=b.m;a.v=aa.standardFragmentHeader+b.code;a.C=aa.vshader;a.h=new La(a.C,a.v);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);var b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),c=n.getAttribLocation(a.h.h,"aPos");n.enableVertexAttribArray(c);a=n.getAttribLocation(a.h.h,"aTexCoord");n.enableVertexAttribArray(a);var d=new Float32Array([0,0,1,0,0,1,1,1]),e=b.byteLength;n.bufferData(n.ARRAY_BUFFER,e+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,
0,b);n.bufferSubData(n.ARRAY_BUFFER,e,d);n.vertexAttribPointer(c,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(a,2,n.FLOAT,!1,0,e)}
function Qa(a){for(var b in a.i){var c=a.l.evaluateAndVal(a.i[b].A),d=a.i[b].type;if(!B(oa(c),d)){console.log("Type of "+b+" changed; forcing rebuild.");Na(a);n.useProgram(a.h.h);Qa(a);return}var e=a.h.i[b];if(void 0!==e)switch(d){case A:e([c.value.real,c.value.imag]);break;case x:c.value?e([1]):e([0]);break;case y:case z:e([c.value.real]);break;case C:case D:case F:var f=0;d===C&&(f=2);d===D&&(f=3);d===F&&(f=4);for(var d=[],g=0;g<f;g++)d.push(c.value[g].value.real);e(d);break;case H:case ra:case sa:f=
0;d===H&&(f=2);d===ra&&(f=3);d===sa&&(f=4);d=[];for(g=0;g<f;g++)for(var p=0;p<f;p++)d.push(c.value[p].value[g].value.real);e(d);break;case G:e([c.value[0].value.real,c.value[0].value.imag,c.value[1].value.real,c.value[1].value.imag]);break;case qa:f=Array(16);for(d=0;2>d;d++)for(g=0;2>g;g++)p=c.value[d].value[g].value,f[8*g+2*d]=p.real,f[4*(2*g+1)+2*d+1]=p.real,f[4*(2*g+1)+2*d]=-p.imag,f[8*g+2*d+1]=p.imag;e(f);break;default:console.error("Don't know how to set uniform"+b+", which has the type "+J(d)+
", to "+c)}}a.h.i.hasOwnProperty("rnd_")&&a.h.i.rnd_([Math.random()])};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,d,e,f,g,p){if(!b.P||b.O<fa)b.P=!0,b.O=fa,b.S=new Ma(a,b);b=b.S;var l=g/f,k=d.x+-(e.y-d.y)*l,l=d.y+(e.x-d.x)*l;va(f,g);p?n.viewport(0,0,f,g):n.viewport(0,h.height-g,f,g);n.useProgram(b.h.h);Qa(b);d=[e.x-d.x,k-d.x,d.x,e.y-d.y,l-d.y,d.y,0,0,1];b.h.i.hasOwnProperty("transformMatrix")&&b.h.i.transformMatrix([d[0],d[3],d[6],d[1],d[4],d[7],d[2],d[5],d[8]]);d=0;for(var t in b.m)for(var E in b.m[t]){n.activeTexture(n.TEXTURE0+d);g=b.m[t][E];e=g.name;
f={H:g.F.hasOwnProperty("interpolate")?g.l.evaluateAndVal(g.F.interpolate).value:!0,D:g.F.hasOwnProperty("mipmap")?g.l.evaluateAndVal(g.F.mipmap).value:!1,repeat:g.F.hasOwnProperty("repeat")?g.l.evaluateAndVal(g.F.repeat).value:!1};l=g;g=f;k=l.l.evaluateAndVal(l.A).value;l="string"===typeof k?l.l.getImage(k,!0):k;null==l?(console.error("Could not find image "+k+"."),g=q):g=Ha(l,g);k=g;if(k.canvas.live||k.canvas.ready&&!(k.generation>=k.canvas.generation)){if(k.w!=k.canvas.width||k.s!=k.canvas.height){k.w=
k.canvas.width;k.s=k.canvas.height;Ka(k);for(var l=Ea(k.G*k.B*4),K=0;2>K;K++)n.bindTexture(n.TEXTURE_2D,k.i[K]),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,k.G,k.B,0,n.RGBA,Fa(),l)}k.bindTexture();n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,1);k.h.repeat?(m.width=k.G,m.height=k.B,l=m.getContext("2d"),l.drawImage(k.canvas.img,0,k.B-k.s),l.drawImage(k.canvas.img,k.w,k.B-k.s),l.drawImage(k.canvas.img,0,k.B-2*k.s),l.drawImage(k.canvas.img,k.w,k.B-2*k.s),n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Fa(),m)):n.texSubImage2D(n.TEXTURE_2D,
0,0,0,n.RGBA,Fa(),k.canvas.img);k.h.D&&n.generateMipmap(n.TEXTURE_2D);n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,0);k.generation=k.canvas.generation;console.log("Image has been loaded to GPU")}g.bindTexture();b.h.i["_sampler"+e]([d]);b.h.i["_ratio"+e]([g.w/g.s]);b.h.i["_cropfact"+e]([g.w/g.G,g.s/g.B]);b.h.i["_repeat"+e]([f.repeat]);b.h.i["_mipmap"+e]([f.D]);d++}p?(p.bindFramebuffer(),p.generation=++p.canvas.generation):n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();p&&
(p.generation=Math.max(p.generation,p.canvas.generation+1))}q=a.nada;a.defineFunction("compile",1,function(b){b=Oa(new Pa(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){fa++;return q});a.defineFunction("colorplot",1,function(c){ha();var d=a.instance.canvas.clientWidth,e=a.instance.canvas.clientHeight,f=a.instance.canvas.width,g=a.instance.canvas.height;b(c[0],xa(a),ya(a),f,g,null);a.instance.canvas.getContext("2d").drawImage(h,0,0,f,g,0,0,d,
e);return q});a.defineFunction("colorplot",3,function(c){ha();var d=c[0],e=a.extractPoint(a.evaluateAndVal(c[1])),f=a.extractPoint(a.evaluateAndVal(c[2])),g={x:Math.min(e.x,f.x),y:Math.min(e.y,f.y)},p={x:Math.max(e.x,f.x),y:Math.min(e.y,f.y)};c=a.instance.canvas.clientWidth;var l=a.instance.canvas.clientHeight,k=a.instance.canvas.width,t=a.instance.canvas.height,E=wa(a,0,0),K=xa(a),za=ya(a),za=Math.abs((e.x-f.x)/(K.x-za.x)),E=Math.abs((e.y-f.y)/(E.y-K.y));b(d,g,p,k*za,t*E,null);d=a.instance.canvas.getContext("2d");
g=Math.min(e.x,f.x);e=Math.max(e.y,f.y);f=a.getInitialMatrix();d.drawImage(h,0,0,k*za,t*E,g*f.a-e*f.b+f.tx,g*f.c-e*f.d-f.ty,za*c,E*l);return q});a.defineFunction("colorplot",4,function(c){ha();var d=a.extractPoint(a.evaluateAndVal(c[0])),e=a.extractPoint(a.evaluateAndVal(c[1])),f=a.evaluateAndVal(c[2]);c=c[3];if(!d.ok||!e.ok||"string"!==f.ctype)return q;var f=a.getImage(f.value,!0),g=Ja(f);b(c,d,e,f.width,f.height,g);return q});a.defineFunction("colorplot",2,function(c){ha();var d=xa(a),e=ya(a),f=
a.evaluateAndVal(c[0]);c=c[1];if("string"!==f.ctype)return q;var f=a.getImage(f.value,!0),g=Ja(f);b(c,d,e,f.width,f.height,g);return q});a.defineFunction("setpixel",4,function(b){var d;var e=a.evaluateAndVal(b[0]),f;f=void 0===f?null:f;"string"===e.ctype?d=e.value:(console.log("argument is not a string"),d=f);e=Ra(a.evaluateAndVal(b[1]));f=Ra(a.evaluateAndVal(b[2]));b=Sa(a.evaluateAndVal(b[3]));if(!d)return q;var g=a.getImage(d,!0),g=Ja(g);isFinite(e)&&isFinite(f)&&d&&g&&b&&(g.bindTexture(),d=[b[0],
b[1],b[2],1],n.texSubImage2D(n.TEXTURE_2D,0,e,f,1,1,n.RGBA,Fa(),Da(d)),b=g.canvas.img.getContext("2d"),g=b.createImageData(1,1),g.data.d=d,b.putImageData(g,e,f));return q})});function B(a,b){return a===b||a===Ta?!0:la(a)&&la(b)?void 0===w[a]?!1:1073741824>w[a][b]:!1}var L=0;function pa(a,b){var c=void 0;if(B(b,a))return a;if(B(a,b)||!la(a))return b;if(!la(b))return a;for(var d=0;d<L;d++)B(a,d)&&B(b,d)&&(void 0===c?c=d:B(d,c)&&(c=d));return c}function Ua(a){return{index:a,type:"template"}}var M={};
function Va(a,b){for(var c in M[a]){for(var d=M[a][c],e=b.length===d.f.length,f={},g=0;g<b.length&&e;g++)"template"===d.f[g].type?(void 0===f[d.f[g].index]&&(f[d.f[g].index]=[]),f[d.f[g].index].push(b[g])):e&=B(b[g],d.f[g]);if(e){var p={},l;for(l in f){p[l]=f[l][0];for(var k in f[l])p[l]=pa(p[l],f[l][k]),void 0===p[l]&&(e=!1)}if(e){a={f:[]};for(g=0;g<b.length&&e;g++)a.f[g]="template"===d.f[g].type?p[d.f[g].index]:d.f[g];a.g="template"===d.g.type?p[d.g.index]:d.g;return a}}}return q};var x=1,y=2,z=3,A=4,C=6,D=7,F=8,H=11,ra=12,sa=13,I=14,G=16,qa=17,Ta=18,Wa={U:x,Y:y,X:z,V:A,ha:5,da:C,fa:D,ga:F,color:9,ca:10,Z:H,aa:ra,ba:sa,image:I,W:15,ea:G,$:qa,T:Ta};Object.freeze(Wa);function J(a){return"bool int float complex voidt float[2] float[3] float[4] color point float[2,2] float[3,3] float[4,4] image 2D-Coordinate complex[2] complex[2,2] anytype".split(" ")[a-1]}v[x]=[y];v[y]=[z];v[z]=[A,9];v[D]=[9,10];v[F]=[9];v[10]=[15];v[C]=[15,G];v[A]=[15];v[H]=[qa];
var Xa={f:[x],g:x},Ya={f:[x,x],g:x},Za={f:[y],g:y},N={f:[y,y],g:y},$a={f:[],g:z},O={f:[z],g:z},P={f:[z,z],g:z},Q={f:[A],g:A},R={f:[A,A],g:A},ab={f:[C,C],g:C},bb={f:[G,G],g:G},cb={f:[D,D],g:D},db={f:[F,F],g:F},eb={f:[z],g:A},S={f:[A],g:z},fb={f:[A,A],g:z},gb={f:[C],g:z},hb={f:[D],g:z},ib={f:[F],g:z},jb={f:[C,C],g:z},kb={f:[D,D],g:z},lb={f:[F,F],g:z},mb={f:[y,y],g:x},nb={f:[z,z],g:x},T=Ua(1),ob=Ua(2),pb=Ua(3);M.sqrt=[eb,Q];M.abs=[O,S,gb,hb,ib];M.exp=[O,Q];M.log=[eb,Q];M.sin=[O,Q];M.cos=[O,Q];
M.tan=[O,Q];M.arccos=[eb,Q];M.arcsin=[eb,Q];M.arctan=[O,Q];M.arctan2=[P,R,S,{f:[C],g:z},{f:[G],g:A}];M.add=[N,P,R,ab,cb,db,bb];M.sub=[N,P,R,ab,cb,db,bb,{f:[5,y],g:y},{f:[5,z],g:z},{f:[5,A],g:A},{f:[5,C],g:C},{f:[5,D],g:D},{f:[5,F],g:F}];M.mult=[N,P];var qb=[A,C,D,F];qb.forEach(function(a){M.mult.push({f:[z,a],g:a});M.mult.push({f:[a,z],g:a})});M.mult=M.mult.concat([R,{f:[H,C],g:C},{f:[qa,G],g:G},{f:[ra,D],g:D},{f:[sa,F],g:F}]);M.mult.push(jb);M.mult.push(kb);M.mult.push(lb);M.mult.push({f:[A,G],g:G});
M.mult.push({f:[G,A],g:G});M.div=[P,R];qb.forEach(function(a){M.div.push({f:[a,z],g:a})});M.div.push({f:[G,A],g:G});M.pow=[{f:[z,y],g:z},{f:[A,A],g:A}];M.re=[S];M.conjugate=[Q];M.im=[S];M.round=[{f:[z],g:y},{f:[A],g:A}];M.floor=[{f:[z],g:y},{f:[A],g:A}];M.ceil=[{f:[z],g:y},{f:[A],g:A}];M.mod=[N,P,R];M.random=[$a,O,Q];M.randominteger=[Za];M.randomint=[Za];M.seedrandom=[{f:[z],g:5}];M.randombool=[{f:[],g:x}];M.randomnormal=[{f:[],g:z}];M.dist=[P,fb,jb,kb,lb];
M._=[{f:[C,y],g:z},{f:[D,y],g:z},{f:[F,y],g:z},{f:[G,y],g:A}];M["^"]=M.pow;M["*"]=M.mult;M["/"]=M.div;M["+"]=M.add;M["-"]=M.sub;[">","<",">=","<=","=="].forEach(function(a){return M[a]=[mb,nb]});M["&"]=[Ya];M["%"]=[Ya];M["="]=[{f:[T,ob],g:ob}];M[";"]=[{f:[T,5],g:T},{f:[T,ob],g:ob},{f:[T],g:T}];M.abs_infix=M.abs;M.dist_infix=M.dist;M.not=[Xa];M.and=[Ya];M.or=[Ya];M.xor=[Ya];"red green blue gray grey hue".split(" ").forEach(function(a){return M[a]=[{f:[z],g:D}]});
M["if"]=[{f:[x,T,T],g:T},{f:[x,T,ob],g:5},{f:[x,T],g:T}];M.repeat=[{f:[y,T],g:T}];M.apply=[{f:[{type:"list",length:T,R:ob},{type:"expression",f:ob,g:pb}],g:{type:"list",length:T,R:pb}}];M.min=[N,P];M.max=[N,P];M.complex=[{f:[C],g:A}];M.re=[S];M.im=[S];M.genList=[{f:[z,z],g:C},{f:[z,z,z],g:D},{f:[z,z,z,z],g:F},{f:[A,A],g:G}];M.imagergb=[{f:[I,15],g:D},{f:[15,15,I,15],g:D}];M.imagergba=[{f:[I,15],g:F},{f:[15,15,I,15],g:F}];Object.freeze(M);for(var rb in Wa)var sb=Wa[rb]+1,tb=L,L=tb>sb?tb:sb;
for(var w=Array(L),ga=Array(L),ub=0;ub<L;ub++){w[ub]=Array(L);ga[ub]=Array(L);for(var vb=0;vb<L;vb++)w[ub][vb]=1073741824,ga[ub][vb]=-1;w[ub][ub]=0}for(var wb=0;wb<L;wb++)for(var xb in v[wb]){var yb=v[wb][xb];w[wb][yb]=1;ga[wb][yb]=yb}for(var zb=0;zb<L;zb++)for(var Ab=0;Ab<L;Ab++)for(var Bb=0;Bb<L;Bb++)w[Ab][zb]+w[zb][Bb]<w[Ab][Bb]&&(w[Ab][Bb]=w[Ab][zb]+w[zb][Bb],ga[Ab][Bb]=ga[Ab][zb]);Object.freeze(v);Object.freeze(w);Object.freeze(ga);var U={};function Cb(a,b,c){if(!c.K.hasOwnProperty(a)){c.K[a]=!0;for(var d in U[a])Cb(U[a][d],b,c);c.L.push(aa[a])}}function V(a){return function(b,c,d){Cb(a,c,d);return W(a)(b)}};function Pa(a){this.v={};this.o={};this.h={};this.u={};this.K={};this.L=[];this.N={};this.M=[];this.C=!1;this.i={};this.l=a;this.m={}}function Db(a,b,c,d){if(!B(c,d))return console.error(J(c)+" is no subtype of "+J(d)+" (trying to cast the term "+b+")"),b;if(c===d||c===Ta)return b;var e=ga[c][d];return X.hasOwnProperty(c)&&X[c].hasOwnProperty(e)?Db(a,X[c][e](b,{},a),e,d):(console.error("CindyGL: No type-inclusion function for "+J(c)+" to "+J(e)+" found. \n Using identity"),Db(a,b,e,d))}
function Eb(a,b,c){if(b.isuniform)return a.u[b.uvariable].type;if("variable"===b.ctype){b=b.name;if("#"===b)return C;if(a.h.hasOwnProperty(c)&&a.h[c].hasOwnProperty(b))return a.h[c][b];if(a.h.hasOwnProperty("")&&a.h[""].hasOwnProperty(b))return a.h[""][b]}else if("function"===b.ctype&&a.i.hasOwnProperty(b.oper)){if(a.h.hasOwnProperty("")&&a.h[""].hasOwnProperty(b.oper))return a.h[""][b.oper]}else{if("number"===b.ctype)return 0!==b.value.imag?A:(b.value.real|0)===b.value.real?y:z;if("void"===b.ctype)return 5;
if("field"===b.ctype)return z;if("string"===b.ctype)return I;for(var d=Array(b.args.length),e=0;e<b.args.length;e++)d[e]=Fb(a,b.args[e],c);a=Va(na(b.oper),d);return void 0===a||a===q?q:a.g}return q}function Fb(a,b,c){a.C&&b.hasOwnProperty("computedType")||(b.computedType=Eb(a,b,c));return b.computedType}
function Gb(a,b){function c(a,b){d.hasOwnProperty(b)||(d[b]=[]);e.hasOwnProperty(b)||(e[b]={});for(var l in a.args)c(a.args[l],b);if("="===a.oper){var k=a.args[0].name;l=b;-1===d[b].indexOf(k)&&(l="",-1===d[l].indexOf(k)&&(d[l].push(k),e[l][k]=[]));e[l][k].push({A:a.args[1],I:b})}else if(void 0!==a.oper&&"regional"===na(a.oper))for(k=0;k<a.args.length;k++)"variable"===a.args[k].ctype&&(l=a.args[k].name,-1===d[b].indexOf(l)&&(d[b].push(l),e[b][l]=[]));else if("function"===a.ctype&&f.hasOwnProperty(a.oper)){l=
a.oper;d.hasOwnProperty(l)||(d[l]=[]);e.hasOwnProperty(l)||(e[l]={});for(k in f[l].arglist){var t=f[l].arglist[k].name;d[l].push(t);e[l].hasOwnProperty(t)||(e[l][t]=[]);e[l][t].push({A:a.args[k],I:b})}c(f[l].body,l);-1===d[""].indexOf(l)&&(d[""].push(l),e[""][l]=[{A:f[l].body,I:l}])}}var d={},e={},f=a.i;c(b,"");a.v=d;a.o=e}
function Hb(a,b){function c(a,b){if(a.hasOwnProperty("dependsOnPixel")&&!0===a.dependsOnPixel)return!0;if("variable"===a.ctype){var d=a.name;return e.hasOwnProperty(b)&&e[b][d]||-1===f[b].indexOf(d)&&e.hasOwnProperty("")&&e[""][d]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}d=["random","verbatimglsl"];if("function"===a.ctype&&-1!=d.indexOf(na(a.oper)))return a.dependsOnPixel=!0;for(var k in a.args)if(c(a.args[k],b))return a.dependsOnPixel=!0;return"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(d=a.oper,
e.hasOwnProperty(d)||(e[d]={}),c(g[d].body,d))?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj,b):!1}function d(a,b){if(c(a,b)){for(var e in a.args)d(a.args[e],b);"field"===a.ctype&&d(a.obj,b);"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(a=a.oper,k.hasOwnProperty(a)||(k[a]=!0,d(g[a].body,a)))}else if("number"!==a.ctype&&"void"!==a.ctype){b=!1;var f,l;for(l in t)!b&&ka(a,t[l].A)&&(b=!0,f=l);b||(f=ua(),t[f]={A:a,type:q});a.isuniform=!0;a.uvariable=f}}var e={"":{"#":!0}},f=a.v,g=a.i,
p;for(p in a.o)for(var l in a.o[p])e.hasOwnProperty(p)||(e[p]={}),e[p][l]=!0;c(b,"");var k={"":!0},t={};d(b,"");a.u=t}function Ib(a,b){if("function"===b.ctype&&!a.i.hasOwnProperty(b.oper)&&null!==a.l.getMyfunction(b.oper)){var c=b.oper;a.i[c]=ja(a.l.getMyfunction(c));Ib(a,a.i[c].body)}for(var d in b.args)Ib(a,b.args[d])}
function Y(a,b,c,d){if(b.isuniform){b=b.uvariable;var e=a.u[b].type;return d?{code:"",j:b,type:e}:{code:""}}if(";"===b.oper){for(var e={type:5,j:""},f="",g=b.args.length-1,p=g;0<=p;p--)"void"===b.args[p].ctype&&g--;for(p=0;p<=g;p++)e=Y(a,b.args[p],c,d&&p===g),f+=e.code;return d?{code:f,j:e.j,type:e.type}:{code:f}}if("="===b.oper)return e=Y(a,b.args[1],c,!0),f=b.args[0].name,b=f+" = "+Db(a,e.j,e.type,Fb(a,b.args[0],c)),d?{code:e.code,j:b,type:a.h[c][f]}:{code:e.code+b+";\n"};if("repeat$2"===b.oper){if("number"!==
b.args[0].ctype)return console.error("repeat possible only for fixed constant number in GLSL"),q;e=ua();f=b.args[0].value.real|0;b=Y(a,b.args[1],c,d);p=g="";d&&(p=ua(),g+=r[b.type]+" "+p+";");g=g+("for(int "+e+"=0; "+e+" < "+f+"; "+e+"++) {\n")+b.code;d&&(g+=p+" = "+b.j+";\n");g+="}\n";return d?{code:g,j:p,type:b.type}:{code:g}}if("repeat$3"===b.oper)console.error("TODO");else{if("if$2"===b.oper||"if$3"===b.oper){var p=Y(a,b.args[0],c,!0),l=Y(a,b.args[1],c,d),f=e="",g=Fb(a,b,c);d&&(f=ua(),e+=r[g]+
" "+f+";");e+=p.code;e+="if("+p.j+") {\n";e+=l.code;d&&(e+=f+" = "+Db(a,l.j,l.type,g)+";\n");"if$3"===b.oper&&(b=Y(a,b.args[2],c,d),e=e+"} else {\n"+b.code,d&&(e+=f+" = "+Db(a,b.j,b.type,g)+";\n"));e+="}\n";return d?{code:e,j:f,type:g}:{code:e}}if("function"===b.ctype||"infix"===b.ctype){var k=b.oper;if("verbatimglsl"===na(k))return b=a.l.evaluateAndVal(b.args[0]).value,d?{j:b,type:Ta,code:""}:{code:b};e=b.args.map(function(b){return Y(a,b,c,!0)});g=e.map(function(a){return a.type});if(a.i.hasOwnProperty(k)){f=
Jb(a,k);p=Array(e.length);for(l=0;l<e.length;l++)p[l]=a.h[k][a.i[k].arglist[l].name];l=a.h[""][k]}else{k=na(k);if("regional"===k)return d?{j:"",type:5,code:""}:{code:""};var t=Va(k,g);if(t===q)return console.error("Could not find a signature for "+k+"("+g.map(J).join(", ")+").\nReturning empty code"),d?{j:"",type:5,code:""}:{code:""};var p=t.f,l=t.g,f=q,E;for(E in u[k])if(ma(u[k][E][0],t)){f=u[k][E][1];break}f===q&&(console.error("There is no webgl-implementation for "+k+"("+t.f.map(J).join(", ")+
").\ndefault: Try glsl-function with same name"),f=function(a){return k+"("+a.join(", ")+")"})}E="";for(var t=Array(e.length),K=0;K<e.length;K++)E+=e[K].code,t[K]=Db(a,e[K].j,g[K],p[K]);b=f(t,b.modifs,a);return d?{j:b,type:l,code:E}:{code:E+b+";\n"}}if("number"===b.ctype)return f=Fb(a,b,c),f===y?e=b.value.real|0:f===z?e=b.value.real:f===A&&(e="vec2( "+b.value.real+", "+b.value.imag+")"),d?{j:e,type:f,code:""}:{code:f+";\n"};if("string"===b.ctype)return console.error("Cannot compile strings to WebGL."),
q;if("variable"===b.ctype)return e=Fb(a,b,c),b=b.name,"#"===b&&(b="cgl_pixel"),d?{j:b,type:e,code:""}:{code:b+";\n"};if("void"===b.ctype)return d?{j:"",type:5,code:""}:{code:""};if("field"===b.ctype)return e=Fb(a,b,c),f=Y(a,b.obj,c,!0).j,f+="."+b.key,d?{j:f,type:e,code:""}:{code:f+";\n"}}console.error("dont know how to this.compile "+JSON.stringify(b))}function Jb(a,b){Kb(a,b,a.i[b].arglist.length);return W(b)}
function Kb(a,b,c){if(!a.N.hasOwnProperty(b)){a.N[b]=!0;for(var d=a.i[b],e=Array(c),f=0;f<c;f++)e[f]=d.arglist[f].name;c=5===r[a.h[""][b]];var f=r[a.h[""][b]]+" "+na(b)+"("+e.map(function(c){return r[a.h[b][c]]+" "+c}).join(", ")+"){\n",g;for(g in a.v[b]){for(var p=!0,l=a.v[b][g],k=0;k<e.length;k++)p&=l!==e[k];p&&(f+=r[a.h[b][l]]+" "+l+";\n")}d=Y(a,d.body,b,!c);f+=d.code;c||(f+="return "+Db(a,d.j,d.type,a.h[""][b])+";\n");a.M.push(f+"}\n")}}
function Oa(a,b){ta=0;var c=b=ja(b);a.C=!1;Ib(a,c);Gb(a,c);Hb(a,c);for(var d in a.u)a.u[d].type=z,c=a.l.evaluateAndVal(a.u[d].A),a.u[d].type=oa(c),console.log("guessed type "+J(a.u[d].type)+" for "+JSON.stringify(a.u[d].A.name));for(d=!0;d;){d=!1;for(var e in a.o)for(var f in a.o[e])for(var g in a.o[e][f]){var c=Fb(a,a.o[e][f][g].A,a.o[e][f][g].I),p=q;a.h.hasOwnProperty(e)&&a.h[e].hasOwnProperty(f)&&(p=a.h[e][f]);var l;c!==q&&(l=p===q?c:B(c,p)?p:pa(p,c),l!==q&&l!==p&&(a.h.hasOwnProperty(e)||(a.h[e]=
{}),a.h[e][f]=l,console.log("variable "+f+" in scope "+e+" got type "+J(l)+" (oltype/othertype is "+J(p)+"/"+J(c)+")"),d=!0))}}a.C=!0;b=Y(a,b,"",!0);e=Db(a,b.j,b.type,9);B(b.type,9)||console.error("expression does not generate a color");var k;f=[];for(k in a.u)a.u[k].type!=I&&f.push("uniform "+r[a.u[k].type]+" "+k+";");k=f.join("\n");f="";for(var t in a.m)for(var E in a.m[t])f+=a.m[t][E].code+"\n";k=k+f+a.L.join("\n");for(var K in a.v[""])t=a.v[""][K],a.i.hasOwnProperty(t)||(k+=r[a.h[""][t]]+" "+
t+";\n");k+=a.M.join("\n");k+="void main(void) {\n"+b.code+"gl_FragColor = "+e+";\n}\n";console.log(k);return{code:k,u:a.u,m:a.m}};function Lb(a,b,c,d){this.A=b;this.l=d;this.F=c;this.name=a;this.code=["uniform sampler2D _sampler",a,";uniform float _ratio",a,";uniform vec2 _cropfact",a,";uniform bool _repeat",a,";uniform bool _mipmap",a,";vec4 _imagergba",a,"(vec2 A, vec2 B, vec2 p) {p -= A; B -= A;float b = dot(B,B);p = vec2(dot(p,B),_ratio",a,"*dot(p,vec2(-B.y,B.x)))/b;if(_repeat",a,") p = mod(p, vec2(1.));if(_repeat",a," && _mipmap",a,") {vec4 color = vec4(0.);float totalWeight = 0.;for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {vec2 delta = .5*vec2(dx, dy);vec2 center = delta+vec2(.5);vec2 tc = fract(p-delta)+delta;float dst = dot(abs(tc-center),vec2(1.));float w = max(.5-dst,0.);w=w*w;color += w * texture2D(_sampler",
a,", tc*_cropfact",a,");totalWeight += w;}return color/totalWeight;}if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)return texture2D(_sampler",a,", p*_cropfact",a,");else return vec4(0.);}"].join("")}function Mb(a,b,c){c.m.hasOwnProperty(a)||(c.m[a]=[]);var d=c.m[a].length,e;for(e in c.m[a])if(d==c.m[a].length){var f=c.m[a][e].F,g=!0,p;for(p in["interpolation","mipmap","repeat"])g&&(ka(f,b)||(g=!1));g&&(d=e)}e=a+"_"+d;d==c.m[a].length&&c.m[a].push(new Lb(e,c.u[a].A,b,c.l));return e};r[x]="bool";r[y]="int";r[z]="float";r[A]="vec2";r[5]="void";r[C]="vec2";r[D]="vec3";r[F]="vec4";r[H]="mat2";r[ra]="mat3";r[sa]="mat4";r[9]="vec4";r[10]="vec3";r[15]="vec2";r[G]="vec4";r[qa]="mat4";Object.freeze(r);function W(a){return function(b){return na(a)+"("+b+")"}}function Z(a){return function(b){return"("+b.join(a)+")"}}function Nb(a){return a}var X={},Ob;for(Ob in Wa)X[Wa[Ob]]={};X[x][y]=W("int");X[y][z]=W("float");X[z][A]=function(a){return"vec2("+a+", 0.)"};X[z][9]=V("float2color");
X[9][D]=function(a){return"("+a+").rgb"};X[9][F]=Nb;X[C][10]=function(a){return"vec3("+a+",1.0)"};X[D][9]=function(a){return"vec4("+a+",1.0)"};X[D][10]=Nb;X[F][9]=Nb;X[10][C]=V("dehomogenize");X[10][D]=Nb;X[10][15]=V("dehomogenize");X[C][15]=Nb;X[A][15]=Nb;X[C][G]=V("vec2complex");X[H][qa]=V("mat2complex");Object.freeze(X);u.sqrt=[[eb,V("sqrtf")],[Q,V("sqrtc")]];u.abs=[[O,W("abs")],[S,W("length")],[gb,W("length")],[hb,W("length")],[ib,W("length")]];u.abs_infix=u.abs;
u.dist=[[P,function(a){return W("abs")(Z("-")(a))}],[fb,function(a){return W("length")(Z("-")(a))}],[jb,function(a){return W("length")(Z("-")(a))}],[kb,function(a){return W("length")(Z("-")(a))}],[lb,function(a){return W("length")(Z("-")(a))}]];u.dist_infix=u.dist;u.sin=[[O,W("sin")],[Q,V("sinc")]];u.cos=[[O,W("cos")],[Q,V("cosc")]];u.tan=[[O,W("tan")],[Q,V("tanc")]];u.exp=[[O,W("exp")],[Q,V("expc")]];u.arctan=[[O,W("atan")],[Q,V("arctanc")]];u.log=[[eb,V("logr")],[Q,V("logc")]];u.add=[];u.sub=[];
[N,P,R,ab,cb,db,bb].forEach(function(a){u.add.push([a,Z("+")]);u.sub.push([a,Z("-")])});function Pb(a){return"-("+a[1]+")"}[y,z,A,C,D,F].forEach(function(a){u.sub.push([{f:[5,a],g:a},Pb])});function Qb(a){return isFinite(a[1])?"("+a[0]+")["+(a[1]-1)+"]":"("+a[0]+")["+a[1]+"-1]"}
u._=[[{f:[C,y],g:z},Qb],[{f:[D,y],g:z},Qb],[{f:[F,y],g:z},Qb],[{f:[G,y],g:A},function(a){if(1===a[1])return"("+a[0]+").xy";if(2===a[1])return"("+a[0]+").zw";console.error("access of components of complex[2] only works for indeces that were hardcoded in CindyJS");return"ERROR: SEE CONSOLE (index was "+a[1]+") \n"}]];u["+"]=u.add;u["-"]=u.sub;
u.mult=[[N,Z("*")],[P,Z("*")],[R,V("multc")],[{f:[H,C],g:C},Z("*")],[{f:[qa,G],g:G},Z("*")],[{f:[ra,D],g:D},Z("*")],[{f:[sa,F],g:F},Z("*")],[jb,W("dot")],[kb,W("dot")],[lb,W("dot")]];qb.forEach(function(a){u.mult.push([{f:[z,a],g:a},Z("*")]);u.mult.push([{f:[a,z],g:a},Z("*")])});u.mult.push([{f:[A,G],g:G},V("multcv")]);u.mult.push([{f:[G,A],g:G},function(a){return V("multcv")([a[1],a[0]])}]);u["*"]=u.mult;u.div=[[P,Z("/")],[R,V("divc")]];qb.forEach(function(a){u.div.push([{f:[a,z],g:a},Z("/")])});
u.div.push([{f:[G,A],g:G},V("divcv")]);u["/"]=u.div;u.re=[[S,V("realc")]];u.im=[[S,V("imagc")]];u.floor=[[{f:[z],g:y},function(a){return"int(floor("+a+"))"}],[{f:[A],g:A},W("floor")]];u.round=[[{f:[z],g:y},function(a){return"int(floor("+a+"+.5))"}],[{f:[A],g:A},function(a){return"floor("+a+"+vec2(.5))"}]];u.ceil=[[{f:[z],g:y},function(a){return"int(ceil("+a+"))"}],[{f:[A],g:A},W("ceil")]];u.mod=[[N,function(a,b){return"int("+W("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[P,W("mod")],[R,W("mod")]];
u.random=[[$a,V("random")],[O,function(a,b){return V("random")([],b)+"*"+a[0]}],[Q,function(a,b){return"vec2("+V("random")([],b)+","+V("random")([],b)+")*"+a[0]}]];u.arctan2=[[P,function(a){return"atan("+a[1]+", "+a[0]+")"}],[R,V("arctan2c")],[S,V("arctan2vec2")],[{f:[C],g:z},V("arctan2vec2")],[{f:[G],g:A},V("arctan2vec2c")]];["red","green","blue","gray","hue"].forEach(function(a){return u[a]=[[{f:[z],g:D},V(a)]]});u.grey=u.gray;u.min=[[N,W("min")],[P,W("min")]];u.max=[[N,W("max")],[P,W("max")]];
u.complex=[[{f:[C],g:A},Nb]];u.pow=[[{f:[z,y],g:z},function(a){return"pow("+a[0]+", float("+a[1]+"))"}],[{f:[A,A],g:A},V("powc")]];u["^"]=u.pow;u.re=[[S,function(a){return"("+a+").x"}]];u.conjugate=[[Q,V("conjugate")]];u.im=[[S,function(a){return"("+a+").y"}]];u.genList=[[{f:[z,z],g:C},W("vec2")],[{f:[z,z,z],g:D},W("vec3")],[{f:[z,z,z,z],g:F},W("vec4")],[{f:[A,A],g:G},W("vec4")]];u["&"]=[[Ya,Z("&&")]];u["%"]=[[Ya,Z("||")]];[">","<",">=","<=","=="].forEach(function(a){return u[a]=[[mb,Z(a)],[nb,Z(a)]]});
u.imagergb=[[{f:[I,15],g:D},function(a,b,c){var d=xa(c.l),e=ya(c.l);return["(_imagergba",Mb(a[0],b,c),"(vec2(",d.x,",",d.y,"),vec2(",e.x,",",e.y,"), ",a[1],").rgb)"].join("")}],[{f:[15,15,I,15],g:D},function(a,b,c){return["(_imagergba",Mb(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}]];
u.imagergba=[[{f:[I,15],g:F},function(a,b,c){var d=xa(c.l),e=ya(c.l);return["_imagergba",Mb(a[0],b,c),"(vec2(",d.x,",",d.y,"),vec2(",e.x,",",e.y,"), ",a[1],")"].join("")}],[{f:[15,15,I,15],g:F},function(a,b,c){return["_imagergba",Mb(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}]];Object.freeze(u);U.divc=["multc"];U.divcv=["multcv"];U.powc=["expc","multc","logc"];U.sqrtc=["expc","multc","logc"];U.arccosc=["multc","negc","sqrtc","addc","logc"];U.arcsinc=["multc","negc","sqrtc","addc","logc"];
U.tanc=["sinc","cosc","divc"];U.arctanc=["logc","addc","multc","subc"];U.arctan2c=["logc","divc","sqrtc","multc"];U.arctan2vec2c=["arctan2c"];U.hue=["hsv2rgb"];Object.freeze(U);function Rb(a){var b;b=void 0===b?null:b;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Sa(a){var b;b=void 0===b?[.5,.5,.5]:b;if("number"===a.ctype){var c=Sb(a);if(!isNaN(c))return[c,c,c]}a=Rb(a);return null===a?b:3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return Sb(a)})}
function Ra(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function Sb(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function ia(a){this.h=a}ia.prototype.toString=function(){return this.h};
function La(a,b){var c=n;this.h=c.createProgram();Tb(this,c,c.VERTEX_SHADER,a);Tb(this,c,c.FRAGMENT_SHADER,b);a=this.h;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new ia("Error linking shader:\n"+c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new ia("Error validating shader:\n"+c.getProgramInfoLog(a));var d=this.h,e,f,g,p={},l,k,t,E;b=c.getProgramParameter(d,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a)if(e=c.getActiveUniform(d,a),null!==
e&&(f=e.name.replace(/\]/g,""))){for(l=p;null!==(g=/[.\[]/.exec(f));)k=f.substr(0,g.index),l.hasOwnProperty(k)?l=l[k]:"."===g[0]?l=l[k]={}:l=l[k]=[],f=f.substr(g.index+1);if(1<e.size){g=e.size;E=Array(g);for(k=0;k<g;++k)t=e.name+"["+k+"]",t=Ub(this,c,t,e),E[k]=t;l[f]=E}else t=Ub(this,c,e.name,e),l[f]=t}this.i=p}
function Tb(a,b,c,d){c=b.createShader(c);b.shaderSource(c,d);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(d.split("\n")),new ia("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.h,c)}
function Ub(a,b,c,d){a=b.getUniformLocation(a.h,c);switch(d.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new ia("Unknown data type for uniform "+c);}};
})();//# sourceMappingURL=CindyGL.js.map


